//常量路由
export const constRoutes= [
  {
    path:'/login',
    component:()=>import('@/views/login/index.vue'),
    name:'login',
    meta:{
      title:"登录",
      hidden:true,
    }
  },
  {
    path:'/',
    component:()=>import('@/layout/index.vue'),
    name:'layout',
    meta:{
      title:"布局",
      hidden:false,
    },
    children:[
      {
        path:'home',
        name:'home',
        component:()=>import('@/views/home/index.vue'),
        meta:{
          title:"首页",
          hidden:false,
        },
      },
    ]
  },
  {
    path:'/404',
    component:()=>import('@/views/404/index.vue'),
    name:'404',
    meta:{
      title:"404",
      hidden:true,
    },
  },
  {
    path:'/:pathMatch(.*)*',
    redirect:'/404',
    name:'any',
    meta:{
      title:"其他",
      hidden:true,
    },
  }
]
